# Generated by Django 5.2.9 on 2026-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_code',
            new_name='dial_code',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.FileField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.FileField(upload_to='review'),
        ),
    ]
