# Generated by Django 5.2.9 on 2026-01-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_country_code_user_dial_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dial_code',
            new_name='dialcode',
        ),
    ]
