# Generated by Django 5.2.9 on 2026-01-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dial_code_user_dialcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dialcode',
            new_name='dial_code',
        ),
    ]
