# Generated by Django 5.2.9 on 2026-01-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dialcode_user_dial_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dial_code',
            new_name='country_code',
        ),
    ]
