# Generated by Django 5.2.9 on 2026-02-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_parent',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='is_parent',
            new_name='parent_size',
        ),
    ]
