# Generated by Django 5.2.9 on 2026-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_is_parent_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
