# Generated by Django 6.0.2 on 2026-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
