# Generated by Django 6.0.2 on 2026-02-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='color',
        ),
    ]
