# Generated by Django 6.0.2 on 2026-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardDetail',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('card_number', models.BigIntegerField(max_length=16)),
                ('card_cvv', models.IntegerField()),
                ('card_expiry', models.IntegerField()),
                ('card_balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
