# Generated by Django 6.0.2 on 2026-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_carddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_choices',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Card')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Captured')], default=0, null=True),
        ),
    ]
