# Generated by Django 6.0.2 on 2026-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_payment_choices_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryPerson',
            fields=[
                ('delivery_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_person_name', models.TextField(max_length=255)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('wallet', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
