# Generated by Django 6.0.2 on 2026-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_deliveryperson_order_delivery_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='delivery_person_name',
            field=models.CharField(max_length=255),
        ),
    ]
