# Generated by Django 6.0.2 on 2026-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_deliveryperson_delivery_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
