# Generated by Django 6.0.2 on 2026-02-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_deliveryperson_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryTokens',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('tokens', models.CharField(max_length=255)),
                ('exp_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.deliveryperson')),
            ],
        ),
    ]
