# Generated by Django 6.0.2 on 2026-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_deliverytokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytokens',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
