# Generated by Django 6.0.2 on 2026-02-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_deliverytokens_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytokens',
            name='password',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
