# Generated by Django 6.0.2 on 2026-02-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_deliverytokens_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='app.deliveryperson'),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Assigned'), (2, 'Accepted'), (3, 'Out for Delivery'), (4, 'Delivered'), (5, 'Cancelled'), (6, 'Failed'), (7, 'Returned')], default=0, null=True),
        ),
        migrations.CreateModel(
            name='orderHistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('delivery_person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.deliveryperson')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
