# Generated by Django 6.0.2 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_deliveryperson_city_order_assigned_delivery_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Assigned'), (2, 'Accepted'), (3, 'Out for Delivery'), (4, 'Delivered'), (5, 'Cancelled'), (6, 'Failed'), (7, 'Returned'), (8, 'Parcel Through')], default=0, null=True),
        ),
    ]
