# Generated by Django 6.0.2 on 2026-03-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
