# Generated by Django 6.0.2 on 2026-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='card_number',
            field=models.BigIntegerField(),
        ),
    ]
