# Generated by Django 6.0.2 on 2026-03-13 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_carddetail_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalInformation',
            fields=[
                ('additional_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('label_data', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
