# Generated by Django 6.0.2 on 2026-03-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_color_remove_product_color_product_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
    ]
