# Generated by Django 6.0.2 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_colors_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
