# Generated by Django 6.0.2 on 2026-03-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_color_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.color'),
        ),
    ]
