# Generated by Django 6.0.2 on 2026-03-27 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cartitems_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.color'),
        ),
    ]
